Repository nebari-dev/nebari-docs, pull requests merged in 2022-09, with the labels that each got.

#133 [DOC] Nebari FAQ page
  docs/docs/faq.md
  docs/sidebars.js
Labels: area: documentation 📖, needs: review 👀

#143 ENH - Update design assets
  README.md
  docs/README.md
  docs/docs/faq.md
  docs/docs/getting-started/deploy.mdx
  docs/docs/troubleshooting.mdx
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/scss/core.scss
  docs/src/scss/utils/_global_vars.scss
  docs/static/logo/Nebari-logo-square.png
  docs/static/logo/Nebari-logo-square.svg
  docs/static/logo/favicon.ico
Labels: type: enhancement 💅🏼, area: design 🎨

#145 [ENH] - Update website styling
  docs/docusaurus.config.js
  docs/src/scss/core.scss
  docs/src/scss/utils/_global_vars.scss
  docs/src/theme/components/admonitions.scss
  docs/src/theme/components/footer.scss
  docs/src/theme/components/navbar.scss
  docs/src/theme/components/scrollbar.scss
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: review 👀, area: user experience 👩🏻‍💻, area: developer experience 👩🏻‍💻, area: accessibility ♿️, area: design 🎨
