Repository nebari-dev/nebari-docs, pull requests merged in 2022-08, with the labels that each got.

#98 feat: add search bar to nebari docs
  docs/docusaurus.config.js
  docs/package.json
  docs/yarn.lock
Labels: area: documentation 📖, needs: review 👀

#101 Adding note to deploying nebari section
  docs/docs/how-tos/domain-registry.md
  docs/docs/how-tos/nebari-aws.md
  docs/docs/how-tos/nebari-azure.md
  docs/docs/how-tos/nebari-do.md
  docs/docs/how-tos/nebari-gcp.md
  docs/docs/source/images/cloudflare_account_resources_scr.png
  docs/docs/source/images/cloudflare_auth_1.png
  docs/docs/source/images/cloudflare_permissions_2.1.1.png
  docs/docs/source/images/cloudflare_summary.png
  docs/docs/source/images/cloudflare_zone_resources.png
Labels: area: documentation 📖, needs: review 👀, area: developer experience 👩🏻‍💻, content: doc/how-to

#71 Tutorial on using vs code
  docs/docs/how-tos/domain-registry.md
  docs/docs/how-tos/kbatch-howto.md
  docs/docs/how-tos/nebari-aws.md
  docs/docs/how-tos/nebari-azure.md
  docs/docs/how-tos/nebari-do.md
  docs/docs/how-tos/nebari-gcp.md
  docs/docs/tutorials/creating-new-environments.md
  docs/docs/tutorials/using_vscode.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/static/img/tutorials/vscode_bashrc.png
  docs/static/img/tutorials/vscode_debug.png
  docs/static/img/tutorials/vscode_extensions.png
  docs/static/img/tutorials/vscode_extensions_list.png
  docs/static/img/tutorials/vscode_files.png
  docs/static/img/tutorials/vscode_hamburger.png
  docs/static/img/tutorials/vscode_launcher.png
  docs/static/img/tutorials/vscode_new_file.png
  docs/static/img/tutorials/vscode_new_file_contents.png
  docs/static/img/tutorials/vscode_output.png
  docs/static/img/tutorials/vscode_run_debug_buttons.png
  docs/static/img/tutorials/vscode_search.png
  docs/static/img/tutorials/vscode_select_env.png
  docs/static/img/tutorials/vscode_source_control.png
  docs/static/img/tutorials/vscode_welcome.png
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: review 👀

#128 📝 Update readmes
  README.md
  docs/README.md
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: review 👀

#58 Dask setup on Nebari : tutorial
  docs/docs/tutorials/using_dask.md
  docs/sidebars.js
  docs/static/img/cluster_creation.png
  docs/static/img/cluster_options.png
  docs/static/img/dask_client.png
  docs/static/img/dask_diagostic_UI.png
  docs/static/img/dask_labextension.png
  docs/static/img/x_array.png
  docs/static/img/z_array.png
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: review 👀, content: doc/tutorial

#97 [DOC] Nebari Troubleshooting page
  docs/docs/getting-started/installing-nebari.md
  docs/docs/troubleshooting.md
  docs/docs/troubleshooting.mdx
  docs/sidebars.js
  docs/static/img/k9s_UI.png
Labels: area: documentation 📖, needs: review 👀

#129 ENH - Improve Docs consistency
  .gitpod.yml
  ARCHITECTURE.md
  docs/README.md
  docs/docs/community/overview.md
  docs/docs/getting-started/cloud-providers.mdx
  docs/docs/getting-started/deploy.mdx
  docs/docs/getting-started/installing-nebari.md
  docs/docs/glossary.md
  docs/docs/governance/overview.md
  docs/docs/how-tos/domain-registry.md
  docs/docs/how-tos/kbatch-howto.md
  docs/docs/how-tos/nebari-aws.md
  docs/docs/how-tos/nebari-azure.md
  docs/docs/how-tos/nebari-do.md
  docs/docs/how-tos/nebari-gcp.md
  docs/docs/how-tos/nebari-hpc.md
  docs/docs/how-tos/nebari-local.md
  docs/docs/troubleshooting.mdx
  docs/docs/tutorials/cost-estimate-report.md
  docs/docs/tutorials/creating-new-environments.md
  docs/docs/tutorials/using-vscode.md
  docs/docs/tutorials/using_dask.md
  docs/docs/welcome.mdx
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/scss/core.scss
  docs/src/scss/utils/_global_vars.scss
  docs/src/theme/components/admonitions.scss
  docs/src/theme/components/footer.scss
  docs/src/theme/components/markdown.scss
  docs/src/theme/components/menu.scss
  docs/src/theme/components/navbar.scss
  docs/static/img/getting-started/started-amazon-web-services-logo.png
  docs/static/img/getting-started/started-azure-logo.png
  docs/static/img/getting-started/started-digital-ocean-logo.png
  docs/static/img/getting-started/started-google-cloud-logo.png
  docs/static/img/getting-started/validate_installation.png
  docs/static/img/how-tos/cloudflare_account_resources_scr.png
  docs/static/img/how-tos/cloudflare_auth_1.png
  docs/static/img/how-tos/cloudflare_permissions_2.1.1.png
  docs/static/img/how-tos/cloudflare_summary.png
  docs/static/img/how-tos/cloudflare_zone_resources.png
  docs/static/img/how-tos/how-tos-aws-new-iam-user.png
  docs/static/img/tutorials/cluster_creation.png
  docs/static/img/tutorials/cluster_options.png
  docs/static/img/tutorials/conda_store_create_env.png
  docs/static/img/tutorials/conda_store_dashboard.png
  docs/static/img/tutorials/conda_store_env_details.png
  docs/static/img/tutorials/conda_store_new_env.png
  docs/static/img/tutorials/dask_client.png
  docs/static/img/tutorials/dask_diagostic_UI.png
  docs/static/img/tutorials/dask_labextension.png
  docs/static/img/tutorials/vscode_bashrc.png
  docs/static/img/tutorials/vscode_welcome.png
  docs/static/img/welcome/nebari_overview_sequence.png
  docs/yarn.lock
Labels: type: enhancement 💅🏼, area: documentation 📖

#138 :bug: Fix broken link
  docs/docs/getting-started/installing-nebari.md
Labels: type: bug 🐛
