Repository nebari-dev/nebari-docs, pull requests merged in 2022-11, with the labels that each got.

#93 [Doc] Add Keycloak login and config docs
  docs/docs/how-tos/configure-keycloak-howto.md
  docs/docs/how-tos/login-thru-keycloak-howto.md
  docs/sidebars.js
  docs/static/img/how-tos/keycloak_add_users.png
  docs/static/img/how-tos/keycloak_adduser.png
  docs/static/img/how-tos/keycloak_groups.png
  docs/static/img/how-tos/keycloak_master_login.png
  docs/static/img/how-tos/keycloak_nebari_login.png
  docs/static/img/how-tos/keycloak_new_group1.png
  docs/static/img/how-tos/keycloak_new_group2.png
  docs/static/img/how-tos/keycloak_new_group3.png
  docs/static/img/how-tos/keycloak_root_user_account_security.png
  docs/static/img/how-tos/keycloak_root_user_manage_account.png
  docs/static/img/how-tos/keycloak_root_user_update_password.png
  docs/static/img/how-tos/keycloak_start_event_logs.png
  docs/static/img/how-tos/keycloak_user_password.png
  docs/static/img/how-tos/nebari_kernel_selection.png
  docs/static/img/how-tos/nebari_login_screen.png
  docs/static/img/how-tos/nebari_main_hub_page.png
  docs/static/img/how-tos/nebari_select_profile.png
  docs/static/img/how-tos/nebari_server_start.png
Labels: area: documentation 📖

#141 DOCS: Add a debugging page for Nebari
  .pre-commit-config.yaml
  docs/docs/community/nebari-tests.md
  docs/docs/how-tos/debug-nebari.mdx
  docs/docs/troubleshooting.mdx
  docs/sidebars.js
  docs/static/img/how-tos/k9s_UI.png
Labels: area: documentation 📖, needs: changes 🧱, content: doc/how-to

#207 First draft Nebari landing page
  docs/docusaurus.config.js
  docs/src/pages/index.jsx
  docs/src/pages/index.mdx
  docs/src/pages/index.module.css
  docs/static/icons/right-arrow-light.svg
  docs/static/img/home/aws.svg
  docs/static/img/home/azure.svg
  docs/static/img/home/clear-ml.svg
  docs/static/img/home/conda-store.svg
  docs/static/img/home/dashboard.png
  docs/static/img/home/digital-ocean.svg
  docs/static/img/home/gcloud.svg
  docs/static/img/home/grafana.svg
  docs/static/img/home/jar-plant.svg
  docs/static/img/home/jupyter.svg
  docs/static/img/home/leaves-circle.svg
  docs/static/img/home/prefect.svg
  docs/static/img/home/roots-plant.svg
  docs/static/img/home/scissor-string.svg
  docs/static/img/home/three-frames.svg
  docs/static/img/home/two-plants.svg
  docs/static/img/home/vscode.svg
  docs/static/logo/Nebari-logo-square.svg
Labels: type: enhancement 💅🏼, area: community 🪴

#213 MAINT - Update pre-commit hooks
  .pre-commit-config.yaml
  ARCHITECTURE.md
  docs/docs/references/RELEASE.md
Labels: type: maintenance 🛠, needs: review 👀, area: dependencies 📦

#223 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/general-issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: file sync ♻️

#226 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
Labels: type: file sync ♻️

#225 Update GitHub links in navbar and footer
  docs/docusaurus.config.js
Labels: type: enhancement 💅🏼, area: documentation 📖

#224 Change some landing page integrations
  docs/src/pages/index.jsx
  docs/static/img/home/argo.svg
  docs/static/img/home/clear-ml.svg
  docs/static/img/home/jitsi.svg
  docs/static/img/home/prefect.svg
Labels: type: enhancement 💅🏼, area: design 🎨

#227 Update Nebari overview sequence in docs/welcome
  docs/static/img/welcome/nebari_overview_sequence.png
Labels: type: enhancement 💅🏼, area: design 🎨
