Repository nebari-dev/nebari-docs, pull requests merged in 2022-06, with the labels that each got.

#33 CI Caching for Docs
  .github/workflows/deploy.yml
  .github/workflows/test-website.yml
  docs/package.json
Labels: type: enhancement 💅🏼, area: CI/CD 👷🏽‍♀️, impact: low

#72 chore: make sidebars collapsible
  docs/docusaurus.config.js
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: review 👀, area: user experience 👩🏻‍💻, impact: low

#51 Update the readme
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: area: documentation 📖, status: in progress 🏗, needs: review 👀
