Repository nebari-dev/nebari-docs, pull requests merged in 2022-07, with the labels that each got.

#67 [MAINT]- Docs theme improvement
  docs/README.md
  docs/css/custom.css
  docs/css/custom.css.map
  docs/css/custom.scss
  docs/docs/tutorials/creating-cds-dashboard.md
  docs/docusaurus.config.js
  docs/package.json
  docs/src/scss/application.scss
  docs/src/scss/core.scss
  docs/src/scss/utils/_global_vars.scss
  docs/src/theme/components/admonitions.scss
  docs/src/theme/components/footer.scss
  docs/src/theme/components/markdown.scss
  docs/src/theme/components/menu.scss
  docs/src/theme/components/navbar.scss
  docs/src/theme/components/scrollbar.scss
  docs/static/icons/edit-dark.svg
  docs/static/icons/edit.svg
  docs/static/icons/github-dark.svg
  docs/static/icons/github-light.svg
  docs/static/icons/moon.svg
  docs/static/icons/sun.svg
  docs/yarn.lock
  package.json
  yarn.lock
Labels: type: enhancement 💅🏼, area: accessibility ♿️, area: design 🎨

#81 Create Main page
  docs/docs/welcome.md
  docs/docs/welcome.mdx
  docs/static/img/nebari_overview_sequence.png
Labels: type: enhancement 💅🏼, area: documentation 📖, status: in progress 🏗, needs: review 👀

#85 [MAINT] - Edits to Dashboard tutorial
  README.md
  docs/docs/tutorials/creating-cds-dashboard.md
  docs/static/img/tutorials/nebari_dashboard_panel.png
  docs/static/img/tutorials/nebari_jupyterlab_file_menu.png
  docs/static/img/tutorials/nebari_window_dashboard_starting_up.png
  docs/static/img/tutorials/trees-dashboard-example.png
  docs/static/img/tutorials/window_dashboard_configuration_example.png
  docs/static/img/tutorials/window_nebari_select_instance_type.png
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: review 👀, content: doc/tutorial

#90 :construction_worker: Add pre-commit action
  .github/workflows/deploy-website.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test-website.yml
  .gitignore
  .pre-commit-config.yaml
  docs/README.md
Labels: type: maintenance 🛠, area: developer experience 👩🏻‍💻, area: CI/CD 👷🏽‍♀️

#77 DOCS: Add an Infracost tutorial
  docs/docs/tutorials/cost-estimate-report.md
  docs/sidebars.js
Labels: type: enhancement 💅🏼, needs: review 👀, content: doc/tutorial

#92 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/general-issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: type: file sync ♻️

#78 DOCS: Tutorial for creating new environments
  docs/docs/tutorials/creating-new-environments.md
  docs/sidebars.js
  docs/static/img/tutorials/conda_store_build_details_bottom.png
  docs/static/img/tutorials/conda_store_build_details_top.png
  docs/static/img/tutorials/conda_store_create_env.png
  docs/static/img/tutorials/conda_store_dashboard.png
  docs/static/img/tutorials/conda_store_env_details.png
  docs/static/img/tutorials/conda_store_login.png
  docs/static/img/tutorials/conda_store_new_env.png
Labels: type: enhancement 💅🏼, area: documentation 📖, status: in progress 🏗, needs: review 👀

#76 kbatch docs
  docs/docs/how-tos/kbatch-howto.md
  docs/sidebars.js
Labels: area: documentation 📖, needs: review 👀, content: doc/tutorial
