Repository nebari-dev/nebari-docs, pull requests merged in 2022-12, with the labels that each got.

#233 Typo fixes in quickstart.md
  docs/docs/get-started/quickstart.md
Labels: type: bug 🐛, area: documentation 📖

#234 ENH - Add review guidelines
  docs/docs/community/code-contributions.mdx
  docs/docs/community/doc-contributions.md
  docs/docs/community/index.mdx
  docs/docs/community/issues.md
  docs/docs/community/maintainers/github-conventions.md
  docs/docs/community/maintainers/reviewer-guidelines.md
  docs/docs/community/maintainers/saved-replies.md
  docs/docs/community/maintainers/triage-guidelines.md
  docs/docs/community/nebari-tests.md
  docs/docs/welcome.mdx
  docs/sidebars.js
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: changes 🧱, area: community 🪴, content: doc/reference

#236 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/config.yml
  CODE_OF_CONDUCT.md
Labels: type: file sync ♻️, status: approved 💪🏾

#237 Update link to CoC in community docs
  docs/docs/community/index.mdx
  docs/docs/community/maintainers/saved-replies.md
Labels: area: documentation 📖, type: maintenance 🛠, area: user experience 👩🏻‍💻, area: developer experience 👩🏻‍💻, area: accessibility ♿️, status: approved 💪🏾

#238 ENH - Add PR labels rationale
  .pre-commit-config.yaml
  docs/docs/community/maintainers/github-conventions.md
Labels: type: enhancement 💅🏼, area: documentation 📖, status: approved 💪🏾, needs: review 👀

#235 Add Nebari local deployment instructions
  docs/docs/how-tos/nebari-local.md
  docs/sidebars.js
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: review 👀

#245 ENH - Enable use of pre-commit.ci moving forward
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
Labels: type: enhancement 💅🏼, area: dependencies 📦, area: CI/CD 👷🏽‍♀️, status: approved 💪🏾

#247 Note about setting CNAME for AWS
  docs/docs/how-tos/domain-registry.md
Labels: type: enhancement 💅🏼, status: approved 💪🏾

#248 Object storage, not block storage
  docs/docs/how-tos/manual-backup.md
Labels: type: bug 🐛, area: documentation 📖, status: approved 💪🏾

#249 Move release details from governance repository
  docs/docs/community/maintainers/release-process.md
Labels: type: maintenance 🛠, area: community 🪴, content: doc/reference, needs: review 👀
