Repository nebari-dev/nebari-docs, pull requests merged in 2022-10, with the labels that each got.

#155 ENH - Add Plausible to site
  docs/docusaurus.config.js
Labels: type: enhancement 💅🏼, area: community 🪴

#154 💄 Fix style in production env
  docs/docusaurus.config.js
  docs/src/scss/core.scss
  docs/src/theme/components/admonitions.scss
Labels: type: bug 🐛, area: documentation 📖, needs: review 👀, area: design 🎨

#149 Typos, links, and small style fixes
  docs/README.md
  docs/docs/getting-started/cloud-providers.mdx
  docs/docs/how-tos/domain-registry.md
  docs/docs/how-tos/nebari-aws.md
  docs/docs/how-tos/nebari-do.md
  docs/docs/how-tos/nebari-gcp.md
  docs/docs/troubleshooting.mdx
  docs/docs/tutorials/cost-estimate-report.md
  docs/docs/tutorials/creating-cds-dashboard.md
  docs/docs/tutorials/creating-new-environments.md
  docs/docs/tutorials/using-vscode.md
  docs/docs/tutorials/using_dask.md
Labels: type: bug 🐛, area: documentation 📖

#165 BUG - Fix links in docs
  docs/src/scss/core.scss
Labels: type: bug 🐛, area: accessibility ♿️, area: design 🎨

#170 Move "Using VS Code" page from Tutorials to How-to's
  docs/docs/how-tos/using-vscode.md
  docs/sidebars.js
Labels: area: documentation 📖, needs: review 👀, status: in review 👀

#166 📝 Updates to readmes
  README.md
  docs/README.md
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: changes 🧱

#171 Update Nebari logo in README
  README.md
Labels: type: bug 🐛, area: documentation 📖, needs: review 👀

#176 Add back "References" in sidebar
  docs/sidebars.js
Labels: area: documentation 📖

#172 Add a documentation style guide
  docs/docs/community/style-guide.md
  docs/sidebars.js
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: review 👀

#180 Clean up the img folder
  docs/docs/troubleshooting.mdx
  docs/static/img/docusaurus.png
  docs/static/img/favicon.ico
  docs/static/img/logo.svg
  docs/static/img/troubleshooting/k9s_UI.png
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
  docs/static/img/x_array.png
  docs/static/img/z_array.png
Labels: type: enhancement 💅🏼, area: documentation 📖

#144 ENH - Replace QHub -> Nebari
  docs/docs/community/issues.md
  docs/docs/community/style-guide.md
  docs/docs/faq.md
  docs/docs/getting-started/cloud-providers.mdx
  docs/docs/getting-started/installing-nebari.md
  docs/docs/how-tos/domain-registry.md
  docs/docs/how-tos/kbatch-howto.md
  docs/docs/how-tos/nebari-aws.md
  docs/docs/how-tos/nebari-azure.md
  docs/docs/how-tos/nebari-do.md
  docs/docs/how-tos/nebari-gcp.md
  docs/docs/how-tos/nebari-hpc.md
  docs/docs/troubleshooting.mdx
  docs/docs/tutorials/creating-cds-dashboard.md
  docs/docs/tutorials/creating-new-environments.md
  docs/docs/tutorials/using_dask.md
  docs/docusaurus.config.js
Labels: area: documentation 📖, needs: review 👀

#186 Add more capitalization references
  docs/docs/community/style-guide.md
Labels: type: enhancement 💅🏼, area: documentation 📖

#142 DOCS: Add Nebari destruction docs
  docs/docs/how-tos/nebari-destroy.md
  docs/sidebars.js
  docs/static/img/how-tos/aws_tag_editor_1.png
  docs/static/img/how-tos/aws_tag_editor_2.png
  docs/static/img/how-tos/aws_tag_editor_3.png
Labels: type: enhancement 💅🏼, area: documentation 📖, content: doc/how-to

#181 Create quickstart commands doc
  docs/docs/getting-started/quickstart.md
  docs/sidebars.js
  docs/static/img/getting-started/nebari-cli-commands.png
Labels: area: documentation 📖

#150 Add nebari typer cli changes
  docs/docs/getting-started/installing-nebari.md
  docs/docs/how-tos/nebari-aws.md
  docs/docs/how-tos/nebari-azure.md
  docs/docs/how-tos/nebari-do.md
  docs/docs/how-tos/nebari-gcp.md
  docs/static/img/getting-started/nebari-help.png
  docs/static/img/getting-started/nebari-init-help-2.png
  docs/static/img/how-tos/nebari-aws.png
  docs/static/img/how-tos/nebari-azure.png
  docs/static/img/how-tos/nebari-deploy-help.png
  docs/static/img/how-tos/nebari-destroy-help.png
  docs/static/img/how-tos/nebari-do.png
  docs/static/img/how-tos/nebari-gcp.png
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: review 👀, impact: high

#178 Add migration steps for conda-store namespaces
  docs/docs/troubleshooting.mdx
  docs/static/img/troubleshooting/delete_namespace.png
Labels: area: documentation 📖, needs: review 👀

#195 Update ARCHITECTURE.md
  ARCHITECTURE.md
Labels: type: bug 🐛, area: documentation 📖

#198 🔄 Synced file(s) with nebari-dev/.github
  CONTRIBUTING.md
Labels: type: file sync ♻️

#191 Create docs for testing Nebari
  docs/docs/community/code-contributions.md
  docs/docs/community/nebari-tests.md
  docs/sidebars.js
Labels: type: enhancement 💅🏼, area: documentation 📖

#202 Fix typo in the style guide
  docs/docs/community/style-guide.md
Labels: type: bug 🐛, area: documentation 📖
