Repository nebari-dev/nebari-docs, pull requests merged in 2023-05, with the labels that each got.

#321 🔄 synced file(s) with nebari-dev/nebari
  docs/docs/references/RELEASE.md
Labels: type: file sync ♻️

#297 Add idle-culling docs
  docs/docs/how-tos/nebari-idle-culler.md
  docs/sidebars.js
Labels: type: enhancement 💅🏼, status: approved 💪🏾

#300 Add docs for deploying nebari on existing k8s
  docs/docs/get-started/deploy.mdx
  docs/docs/how-tos/nebari-kubernets.mdx
  docs/sidebars.js
Labels: type: enhancement 💅🏼, needs: changes 🧱

#329 Rearrange upgrade docs
  docs/docs/faq.md
  docs/docs/how-tos/nebari-upgrade.md
  docs/docs/how-tos/pytorch-best-practices.md
Labels: type: maintenance 🛠, needs: review 👀

#327 🔄 synced file(s) with nebari-dev/nebari
  docs/docs/references/RELEASE.md
Labels: type: file sync ♻️

#303 Add information around built-in namespaces `nebari-git` and `global`
  docs/docs/explanations/advanced-env-configuration.md
Labels: area: documentation 📖, content: doc/reference, needs: review 👀
