Repository nebari-dev/nebari-docs, pull requests merged in 2023-04, with the labels that each got.

#115 [ENH] Add advanced-settings docs
  docs/docs/explanations/advanced-configuration.md
  docs/docs/explanations/advanced-custom-settings.md
  docs/docs/explanations/advanced-customize-themes.md
  docs/docs/explanations/advanced-env-configuration.md
  docs/docs/explanations/advanced-profiles-settings.md
  docs/docs/explanations/advanced-provider-configuration.md
  docs/docs/explanations/advanced-security-configuration.md
  docs/docs/explanations/configuration-best-practices.mdx
  docs/docs/faq.md
  docs/docs/troubleshooting.mdx
  docs/sidebars.js
  docs/static/img/explanations/profiles-server-options.png
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: review 👀

#305 Update contributing guide
  docs/docs/community/code-contributions.mdx
Labels: type: bug 🐛, area: community 🪴

#310 Remove mentions of `environment-dev.yml`
  docs/docs/community/code-contributions.mdx
Labels: type: maintenance 🛠, area: developer experience 👩🏻‍💻, needs: review 👀

#309 Add pytorch best practices page
  docs/docs/faq.md
  docs/docs/how-tos/pytorch-best-practices.md
  docs/sidebars.js
  docs/static/img/how-tos/pytorch-conda-specification.png
  docs/static/img/how-tos/pytorch-installation-matrix.png
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: changes 🧱, area: user experience 👩🏻‍💻

#315 Add docs for installing and setup kubectl
  docs/docs/how-tos/debug-nebari.mdx
  docs/docs/how-tos/manual-backup.md
  docs/docs/how-tos/nebari-local.md
Labels: area: documentation 📖, area: user experience 👩🏻‍💻, needs: review 👀

#320 🔄 Synced file(s) with nebari-dev/.github
  CONTRIBUTING.md
Labels: type: file sync ♻️
