Repository nebari-dev/nebari-docs, pull requests merged in 2023-03, with the labels that each got.

#273 Update k9s docs
  docs/docs/how-tos/debug-nebari.mdx
Labels: area: documentation 📖, impact: low 🟩, area: k8s ⎈, content: doc/how-to

#267 PR: move and combine upgrade docs
  docs/docs/how-tos/nebari-upgrade.md
  docs/sidebars.js
Labels: type: enhancement 💅🏼, status: in review 👀

#286 Update docs for minor upgrade
  docs/docs/how-tos/nebari-upgrade.md
Labels: type: enhancement 💅🏼, status: approved 💪🏾

#283 Update dashboard doc with note about environment info
  docs/docs/faq.md
  docs/docs/tutorials/creating-cds-dashboard.md
Labels: type: maintenance 🛠, status: approved 💪🏾

#268 Migrating old Argo docs and applying minor updates
  docs/docs/how-tos/setup-argo.md
  docs/docs/how-tos/using-argo.md
  docs/sidebars.js
  docs/static/img/tutorials/argo_server_landing_page.png
  docs/static/img/tutorials/argo_workflows_user_tab.png
Labels: type: enhancement 💅🏼, area: integration/Argo, status: in review 👀

#287 Make learning paths move visible
  docs/docs/community/maintainers/github-conventions.md
  docs/docs/community/maintainers/reviewer-guidelines.md
  docs/docs/community/maintainers/saved-replies.md
  docs/docs/community/maintainers/triage-guidelines.md
  docs/docs/faq.md
  docs/docs/get-started/quickstart.md
  docs/docs/how-tos/configure-keycloak-howto.md
  docs/docs/how-tos/login-thru-keycloak-howto.md
  docs/docs/how-tos/nebari-aws.md
  docs/docs/how-tos/nebari-local.md
  docs/docs/how-tos/nebari-upgrade.md
  docs/docs/tutorials/creating-cds-dashboard.md
  docs/docs/welcome.mdx
Labels: type: maintenance 🛠, needs: review 👀
