Repository nebari-dev/nebari-docs, pull requests merged in 2023-09, with the labels that each got.

#334 Document team structure and project roles
  docs/docs/community/team-structure.md
  docs/sidebars.js
Labels: area: community 🪴, status: in review 👀

#350 Argo docs update
  docs/docs/how-tos/using-argo.md
  docs/docs/references/RELEASE.md
  docs/docs/tutorials/argo-workflows-walkthrough.md
  docs/docs/tutorials/run-notebooks-as-a-job.md
  docs/sidebars.js
  docs/static/img/how-tos/argo_landing_page.png
  docs/static/img/how-tos/argo_submit_new_workflow.png
  docs/static/img/how-tos/argo_workflow_details.png
  docs/static/img/tutorials/argo_server_landing_page.png
  docs/static/img/tutorials/argo_workflows_user_tab.png
Labels: type: enhancement 💅🏼, area: integration/Argo, status: approved 💪🏾

#358 Remove dns settings in cli
  docs/docs/how-tos/domain-registry.md
Labels: status: approved 💪🏾

#353 Note about Dask Gateway issue
  docs/docs/troubleshooting.mdx
Labels: type: enhancement 💅🏼, area: integration/Dask, status: in review 👀

#362 Improve Extensions documentation
  docs/docs/community/plugins.md
  docs/docs/how-tos/nebari-extension-system.md
  docs/sidebars.js
Labels: area: community 🪴, status: in review 👀

#366 Remove infracost docs, update in prep for 2023.9.1
  docs/docs/explanations/advanced-custom-settings.md
  docs/docs/faq.md
  docs/docs/how-tos/nebari-aws.md
  docs/docs/tutorials/cost-estimate-report.md
  docs/docs/tutorials/creating-cds-dashboard.md
  docs/docs/welcome.mdx
  docs/sidebars.js
Labels: type: release 🏷, area: user experience 👩🏻‍💻, status: approved 💪🏾, project: JATIC

#367 How to upgrade kubernetes
  docs/docs/how-tos/nebari-upgrade.md
  docs/docs/how-tos/upgrade-kubernetes-version.md
  docs/sidebars.js
Labels: needs: changes 🧱, area: k8s ⎈, provider: AWS, provider: Azure, provider: Digital Ocean, provider: GCP, project: JATIC
