Repository nebari-dev/nebari-docs, pull requests merged in 2023-01, with the labels that each got.

#59 [DOC] Adding architecture documentation to explanations
  docs/docs/explanations/architecture.mdx
  docs/static/img/explanations/architecture-diagram-aws.png
  docs/static/img/explanations/architecture-diagram-azure.png
  docs/static/img/explanations/architecture-diagram-do.png
  docs/static/img/explanations/architecture-diagram-gcp.png
  docs/static/img/explanations/architecture-diagram-high-level.png
  docs/static/img/explanations/architecture-diagram-kubernetes.png
  docs/static/img/explanations/components-of-kubernetes.svg
  docs/static/img/explanations/core-concepts.png
  docs/static/img/explanations/kubernetes-concepts-architecture.jpg
  docs/static/img/explanations/terraform.png
Labels: type: enhancement 💅🏼, area: documentation 📖, needs: changes 🧱, content: doc/conceptual_guide

#258 Add conceptual guides to the sidebar
  docs/docs/explanations/index.mdx
  docs/sidebars.js
Labels: type: maintenance 🛠, status: in review 👀

#250 Review and update Dask tutorial
  docs/docs/community/style-guide.md
  docs/docs/tutorials/using_dask.md
  docs/sidebars.js
  docs/static/img/tutorials/cluster_creation.png
  docs/static/img/tutorials/cluster_options.png
  docs/static/img/tutorials/dask_client.png
  docs/static/img/tutorials/dask_cluster_creation.png
  docs/static/img/tutorials/dask_cluster_options.png
  docs/static/img/tutorials/dask_diagnostic_dashboard.png
  docs/static/img/tutorials/dask_diagostic_UI.png
  docs/static/img/tutorials/dask_labextension.png
Labels: area: documentation 📖, type: maintenance 🛠, area: user experience 👩🏻‍💻, area: integration/Dask, status: in review 👀

#260 Update kbatch docs
  docs/docs/how-tos/kbatch-howto.md
  docs/docs/tutorials/kbatch.md
  docs/docs/welcome.mdx
  docs/sidebars.js
Labels: area: documentation 📖, status: in progress 🏗

#261 Move docs
  docs/docs/faq.md
Labels: type: enhancement 💅🏼, needs: changes 🧱
