Repository nebari-dev/nebari-docs, pull requests merged in 2023-11, with the labels that each got.

#378 Update docs based on admin training and feedback
  docs/docs/explanations/advanced-configuration.md
  docs/docs/how-tos/configure-keycloak-howto.md
  docs/docs/how-tos/nebari-gcp.md
  docs/docs/troubleshooting.mdx
  docs/static/img/troubleshooting/delete_build.png
  docs/static/img/troubleshooting/delete_environment.png
  docs/static/img/troubleshooting/delete_namespace.png
  docs/static/img/troubleshooting/delete_namespace_045_upgrade.png
  docs/static/img/troubleshooting/manage_namespaces.png
Labels: area: documentation 📖, area: integration/conda-store

#374 🔄 synced file(s) with nebari-dev/nebari
  docs/docs/references/RELEASE.md
Labels: type: file sync ♻️

#383 Fix broken `conda-lock` link
  docs/docs/tutorials/creating-new-environments.md
Labels: type: bug 🐛, status: approved 💪🏾

#373 Required gcp services
  docs/docs/how-tos/nebari-gcp.md
Labels: type: enhancement 💅🏼, provider: GCP, status: approved 💪🏾
