Repository nebari-dev/nebari-docs, pull requests merged in 2023-08, with the labels that each got.

#344 🔄 synced file(s) with nebari-dev/nebari
  docs/docs/references/RELEASE.md
Labels: type: file sync ♻️, status: approved 💪🏾

#347 🔄 synced file(s) with nebari-dev/nebari
  docs/docs/references/RELEASE.md
Labels: type: file sync ♻️

#348 Update dev docs to use branch
  docs/docs/community/code-contributions.mdx
Labels: area: documentation 📖, area: developer experience 👩🏻‍💻, status: approved 💪🏾

#352 Add extension-system docs
  docs/docs/how-tos/nebari-extension-system.md
  docs/sidebars.js
Labels: type: enhancement 💅🏼, status: approved 💪🏾
