Repository nebari-dev/nebari-docs, pull requests merged in 2024-05, with the labels that each got.

#399 Update conda-store docs
  docs/docs/tutorials/creating-new-environments.md
  docs/static/img/tutorials/conda_store_build_details_bottom.png
  docs/static/img/tutorials/conda_store_build_details_top.png
  docs/static/img/tutorials/conda_store_create_env.png
  docs/static/img/tutorials/conda_store_dashboard.png
  docs/static/img/tutorials/conda_store_env_details.png
  docs/static/img/tutorials/conda_store_login.png
  docs/static/img/tutorials/conda_store_new_env.png
  docs/static/img/tutorials/conda_store_webui.png
Labels: type: maintenance 🛠, status: blocked ⛔️, needs: changes 🧱

#414 Remove Nebari-HPC docs
  README.md
  docs/docs/get-started/cloud-providers.mdx
  docs/docs/get-started/deploy.mdx
  docs/docs/get-started/installing-nebari.md
  docs/docs/how-tos/nebari-hpc.md
  docs/sidebars.js
  docs/src/pages/index.jsx
Labels: area: documentation 📖, type: maintenance 🛠

#463 Add SMTP Config docs
  docs/docs/how-tos/configure-smtp.md
  docs/sidebars.js
  docs/static/img/how-tos/nebari-smtp.png
Labels: status: in review 👀
