Repository nebari-dev/nebari-docs, pull requests merged in 2024-08, with the labels that each got.

#460 Add nebari user personas
  docs/docs/references/personas.md
  docs/sidebars.js
  docs/static/img/references/alia.png
  docs/static/img/references/blake.png
  docs/static/img/references/enzo.png
  docs/static/img/references/jacob.png
  docs/static/img/references/jordan.png
  docs/static/img/references/noor.png
  docs/static/img/references/robin.png
  docs/static/img/references/sam.png
  docs/static/img/references/skyler.png
  docs/static/img/references/taylor.png
Labels: area: documentation 📖, content: doc/reference, needs: review 👀

#402 Add docs for `helm_extension` mechanism
  docs/docs/explanations/advanced-custom-settings.md
Labels: area: documentation 📖, needs: review 👀

#492 🔄 synced file(s) with nebari-dev/nebari
  docs/docs/references/RELEASE.md
Labels: type: file sync ♻️

#499 🔄 synced file(s) with nebari-dev/nebari
  docs/docs/references/RELEASE.md
Labels: type: file sync ♻️

#497 Rework wording in environment management file
  docs/docs/how-tos/nebari-environment-management.md
Labels: area: documentation 📖, needs: review 👀

#489 Lint all files
  docs/docs/community/decision-making.md
  docs/docs/community/plugins.md
  docs/docs/community/team-structure.md
  docs/docs/explanations/advanced-configuration.md
  docs/docs/faq.md
  docs/docs/get-started/installing-nebari.md
  docs/docs/get-started/quickstart.md
  docs/docs/how-tos/configure-keycloak-howto.md
  docs/docs/how-tos/configure-smtp.md
  docs/docs/how-tos/nebari-environment-management.md
  docs/docs/how-tos/nebari-extension-system.md
  docs/docs/how-tos/nebari-gcp.md
  docs/docs/how-tos/nebari-local.md
  docs/docs/how-tos/nebari-upgrade.md
  docs/docs/how-tos/upgrade-kubernetes-version.md
  docs/docs/how-tos/using-argo.md
  docs/docs/how-tos/using-vscode.md
  docs/docs/references/RELEASE.md
  docs/docs/tutorials/create-dashboard.md
  docs/docs/tutorials/login-with-keycloak.md
  docs/docs/tutorials/run-notebook-as-a-job.md
Labels: type: maintenance 🛠, area: developer experience 👩🏻‍💻, needs: review 👀

#490 Update jhub apps related docs
  docs/docs/how-tos/jhub-app-launcher.md
  docs/docs/tutorials/create-dashboard.md
  docs/docs/tutorials/login-with-keycloak.md
  docs/static/img/how-tos/jhub_apps_home.png
  docs/static/img/how-tos/nebari_login_screen.png
  docs/static/img/tutorials/jhub-apps-create-new-app.png
  docs/static/img/tutorials/jhub-apps-manage-app.png
  docs/static/img/tutorials/nebari-home.png
  docs/static/img/tutorials/trees-dashboard-example.png
Labels: area: dependencies 📦, needs: review 👀

#507 Update Nebari extensions information
  docs/docs/community/plugins.md
Labels: area: documentation 📖, area: dependencies 📦, needs: review 👀

#508 Fix yarn lint/format
  .github/workflows/test-website.yml
  docs/docs/explanations/advanced-custom-settings.md
  docs/docs/how-tos/access-logs-loki.md
  docs/docs/how-tos/jhub-app-launcher.md
  docs/docs/how-tos/nebari-environment-management.md
  docs/docs/references/RELEASE.md
  docs/docs/references/personas.md
  docs/docs/tutorials/create-dashboard.md
Labels: area: documentation 📖, needs: review 👀

#501 Document how to connect via ssh
  docs/docs/how-tos/connect-via-ssh.mdx
  docs/sidebars.js
  docs/static/img/how-tos/jupyterhub-token.png
Labels: area: documentation 📖, needs: review 👀

#493 add rook ceph docs
  docs/docs/explanations/advanced-configuration.md
Labels: needs: review 👀
