Repository nebari-dev/nebari-docs, pull requests merged in 2024-01, with the labels that each got.

#384 Add docs for telemetry/jupyterlab-pioneer
  docs/docs/how-tos/telemetry.md
  docs/sidebars.js
Labels: type: enhancement 💅🏼, needs: review 👀

#387 Fix README.md broken installation link
  README.md
Labels: type: bug 🐛, status: approved 💪🏾

#392 Add docs for permissions boundary
  docs/docs/explanations/advanced-provider-configuration.md
Labels: type: enhancement 💅🏼, needs: review 👀

#391 Add installation docs for JHub App Launcher
  docs/docs/how-tos/jhub-app-launcher.md
  docs/sidebars.js
Labels: type: enhancement 💅🏼, needs: review 👀

#400 Expand installation notes & update good-first-issues link
  docs/docs/community/code-contributions.mdx
Labels: type: enhancement 💅🏼, status: approved 💪🏾
