Repository nebari-dev/nebari-docs, pull requests merged in 2024-09, with the labels that each got.

#484 Add docs around installing packages via pip
  docs/docs/faq.md
  docs/docs/how-tos/develop-local-packages.md
  docs/docs/how-tos/install-pip-packages.md
  docs/sidebars.js
Labels: needs: review 👀

#476 Restructure into multiple instances
  docs/community/code-contributions.mdx
  docs/community/decision-making.md
  docs/community/doc-contributions.md
  docs/community/introduction.mdx
  docs/community/issues.md
  docs/community/maintainers/github-conventions.md
  docs/community/maintainers/release-process.md
  docs/community/maintainers/reviewer-guidelines.md
  docs/community/maintainers/saved-replies.md
  docs/community/maintainers/triage-guidelines.md
  docs/community/nebari-tests.md
  docs/community/plugins.md
  docs/community/style-guide.md
  docs/community/team-structure.md
  docs/docs/get-started/index.mdx
  docs/docs/welcome.mdx
  docs/docusaurus.config.js
  docs/nebari-slurm/overview.mdx
  docs/sidebars.js
  docs/sidebarsCommunity.js
  docs/sidebarsSlurm.js
  docs/src/pages/index.jsx
Labels: status: in progress 🏗

#503 Docusaurus v3 upgrade
  docs/.eslintrc.json
  docs/community/decision-making.md
  docs/community/doc-contributions.md
  docs/community/introduction.mdx
  docs/community/nebari-tests.md
  docs/community/style-guide.md
  docs/community/team-structure.md
  docs/docs/explanations/advanced-env-configuration.md
  docs/docs/get-started/quickstart.md
  docs/docs/how-tos/access-logs-loki.md
  docs/docs/how-tos/configure-keycloak-howto.md
  docs/docs/how-tos/connect-via-ssh.mdx
  docs/docs/how-tos/debug-nebari.mdx
  docs/docs/how-tos/manual-backup.md
  docs/docs/how-tos/nebari-aws.md
  docs/docs/how-tos/nebari-azure.md
  docs/docs/how-tos/nebari-do.md
  docs/docs/how-tos/nebari-gcp.md
  docs/docs/how-tos/nebari-kubernets.mdx
  docs/docs/how-tos/nebari-upgrade.md
  docs/docs/how-tos/use-gpus.mdx
  docs/docs/references/RELEASE.md
  docs/docs/tutorials/login-with-keycloak.md
  docs/docusaurus.config.js
  docs/eslint.config.mjs
  docs/package.json
  docs/src/theme/components/navbar.scss
  docs/yarn.lock
Labels: area: documentation 📖
